"""Add ad platform credentials to client

Revision ID: 598e0a614996
Revises: c291f4e8ccd3
Create Date: 2026-02-21 19:12:46.516950
"""

from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '598e0a614996'
down_revision: Union[str, None] = 'c291f4e8ccd3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('meta_app_id', sa.String(length=100), nullable=True))
    op.add_column('clients', sa.Column('meta_app_secret', sa.String(length=200), nullable=True))
    op.add_column('clients', sa.Column('google_client_id', sa.String(length=200), nullable=True))
    op.add_column('clients', sa.Column('google_client_secret', sa.String(length=200), nullable=True))
    op.add_column('clients', sa.Column('google_developer_token', sa.String(length=200), nullable=True))
    op.add_column('clients', sa.Column('ga4_property_id', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clients', 'ga4_property_id')
    op.drop_column('clients', 'google_developer_token')
    op.drop_column('clients', 'google_client_secret')
    op.drop_column('clients', 'google_client_id')
    op.drop_column('clients', 'meta_app_secret')
    op.drop_column('clients', 'meta_app_id')
    # ### end Alembic commands ###
